version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_dataset:
    run: >
      databuilder:v0 
        generate-dataset analysis/databuilder_definition.py --output output/dataset_all.csv.gz
    outputs:
      highly_sensitive:
        dataset_all: output/dataset_all.csv.gz
  